
import javax.swing.*;
import java.sql.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author extra
 */
public class CarConfigPanel extends javax.swing.JPanel {

    private GarageController gc;
    private JInternalFrame inFrame;
    
    /**
     * Creates new form CarInfoPanel
     */
    public CarConfigPanel(int slot, String customer_name, String car_id,String brand, String model, String status, String date_in, String date_out, GarageController gc, JInternalFrame inFrame) {
        initComponents();
        slotTextField.setText("" + slot);
        customerNameTextField.setText(customer_name);
        brandTextField.setText(brand);
        modelTextField.setText(model);
        carIDTextField.setText(car_id);
        statusSelector.setSelectedItem((Object)status);
        dateInTextField.setText(date_in);
        dateOutTextField.setText(date_out);
        this.gc = gc;
        this.inFrame = inFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField5 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        carIDLabel = new javax.swing.JLabel();
        modelLable = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        carIDTextField = new javax.swing.JTextField();
        brandTextField = new javax.swing.JTextField();
        modelTextField = new javax.swing.JTextField();
        slotTextField = new javax.swing.JTextField();
        statusLabel1 = new javax.swing.JLabel();
        dateInTextField = new javax.swing.JTextField();
        modelLable1 = new javax.swing.JLabel();
        modelLable2 = new javax.swing.JLabel();
        dateOutTextField = new javax.swing.JTextField();
        confirmButton = new javax.swing.JButton();
        customerNameTextField = new javax.swing.JTextField();
        statusSelector = new javax.swing.JComboBox<>();

        jTextField5.setBackground(new java.awt.Color(233, 233, 233));
        jTextField5.setForeground(new java.awt.Color(69, 69, 69));
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 184, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        carIDLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        carIDLabel.setForeground(new java.awt.Color(242, 157, 0));
        carIDLabel.setText("Car_ID :");

        modelLable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        modelLable.setForeground(new java.awt.Color(242, 157, 0));
        modelLable.setText("Model :");

        statusLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        statusLabel.setForeground(new java.awt.Color(242, 157, 0));
        statusLabel.setText("Status :");

        carIDTextField.setBackground(new java.awt.Color(233, 233, 233));
        carIDTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        carIDTextField.setForeground(new java.awt.Color(69, 69, 69));
        carIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carIDTextFieldActionPerformed(evt);
            }
        });

        brandTextField.setBackground(new java.awt.Color(233, 233, 233));
        brandTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        brandTextField.setForeground(new java.awt.Color(69, 69, 69));
        brandTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brandTextFieldActionPerformed(evt);
            }
        });

        modelTextField.setBackground(new java.awt.Color(233, 233, 233));
        modelTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        modelTextField.setForeground(new java.awt.Color(69, 69, 69));
        modelTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelTextFieldActionPerformed(evt);
            }
        });

        slotTextField.setEditable(false);
        slotTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        slotTextField.setText("Slot : 1");
        slotTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slotTextFieldActionPerformed(evt);
            }
        });

        statusLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        statusLabel1.setForeground(new java.awt.Color(242, 157, 0));
        statusLabel1.setText("Brand :");

        dateInTextField.setBackground(new java.awt.Color(233, 233, 233));
        dateInTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dateInTextField.setForeground(new java.awt.Color(69, 69, 69));
        dateInTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateInTextFieldActionPerformed(evt);
            }
        });

        modelLable1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        modelLable1.setForeground(new java.awt.Color(242, 157, 0));
        modelLable1.setText("Date In :");

        modelLable2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        modelLable2.setForeground(new java.awt.Color(242, 157, 0));
        modelLable2.setText("Date Out :");

        dateOutTextField.setBackground(new java.awt.Color(233, 233, 233));
        dateOutTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dateOutTextField.setForeground(new java.awt.Color(69, 69, 69));
        dateOutTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateOutTextFieldActionPerformed(evt);
            }
        });

        confirmButton.setBackground(new java.awt.Color(153, 255, 153));
        confirmButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        confirmButton.setText("Confirm");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        customerNameTextField.setBackground(new java.awt.Color(233, 233, 233));
        customerNameTextField.setFont(new java.awt.Font("IrisUPC", 3, 48)); // NOI18N
        customerNameTextField.setForeground(new java.awt.Color(255, 153, 51));
        customerNameTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        customerNameTextField.setText("Customer_name");
        customerNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerNameTextFieldActionPerformed(evt);
            }
        });

        statusSelector.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        statusSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Not Working", "Working", "Finish", "Ready to out" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(carIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(carIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(statusLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(statusSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(statusLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(brandTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(modelLable)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(modelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(modelLable1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(dateInTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(modelLable2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dateOutTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(55, 55, 55))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(slotTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125)
                        .addComponent(customerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(slotTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(customerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brandTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusLabel)
                    .addComponent(statusLabel1)
                    .addComponent(statusSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modelLable)
                    .addComponent(modelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dateInTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(modelLable1)
                        .addComponent(modelLable2))
                    .addComponent(dateOutTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void carIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carIDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carIDTextFieldActionPerformed

    private void brandTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brandTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brandTextFieldActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void modelTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelTextFieldActionPerformed

    private void slotTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slotTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_slotTextFieldActionPerformed

    private void dateInTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateInTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateInTextFieldActionPerformed

    private void dateOutTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateOutTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateOutTextFieldActionPerformed

    private void customerNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerNameTextFieldActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        int slot = Integer.parseInt(slotTextField.getText());
        String customer_name = customerNameTextField.getText();
        String brand = brandTextField.getText();
        String model = modelTextField.getText();
        String carID = carIDTextField.getText();
        String status_txt = (String)statusSelector.getSelectedItem();
        int status = 0;
        switch(status_txt){
            case "Not Working":
                status = Car.STATUS_NOTWORKING;
                break;
            case "Working":
                status = Car.STATUS_WORKING;
                break;
            case "Finish":
                status = Car.STATUS_FINISH;
                break;
            case "Ready to out":
                status = Car.STATUS_READY_TO_OUT;
                break;
        }
        String date_in = dateInTextField.getText();
        String date_out = dateOutTextField.getText();
        String sql = String.format("update car_list set "
                + "car_owner = '%s', "
                + "brand = '%s', "
                + "car_name = '%s', "
                + "car_id = '%s', "
                + "car_status = %d, "
                + "car_in = '%s', "
                + "car_out = '%s' "
                + "where ch = %d", customer_name, brand, model, carID, status, date_in, date_out, slot);
        try{
            gc.getStatement().executeUpdate(sql);
            gc.getGarage().update();
            gc.update();
            inFrame.dispose();
        }catch(SQLException sqle){
            sqle.printStackTrace();
        }
        
    }//GEN-LAST:event_confirmButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField brandTextField;
    private javax.swing.JLabel carIDLabel;
    private javax.swing.JTextField carIDTextField;
    private javax.swing.JButton confirmButton;
    private javax.swing.JTextField customerNameTextField;
    private javax.swing.JTextField dateInTextField;
    private javax.swing.JTextField dateOutTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel modelLable;
    private javax.swing.JLabel modelLable1;
    private javax.swing.JLabel modelLable2;
    private javax.swing.JTextField modelTextField;
    private javax.swing.JTextField slotTextField;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JLabel statusLabel1;
    private javax.swing.JComboBox<String> statusSelector;
    // End of variables declaration//GEN-END:variables

    public JButton getConfirmButton(){
        return this.confirmButton;
    }

}
