import com.formdev.flatlaf.*;
import javax.swing.*;
public class HomepageFrame extends javax.swing.JFrame implements ChangePageButton {
    protected JPanel[] pnArr;
    protected JButton[] bnArr;
    private HomepageSystem hps;
    /**
     * Creates new form HomePageFrame
     */
    public HomepageFrame(Garage gr, JDesktopPane dtp){
        initComponents();
        hps = new HomepageSystem(gr, dtp);

        pnArr = new JPanel[]{statusPn0, statusPn1, statusPn2, statusPn3, statusPn4, statusPn5, statusPn6, statusPn7, statusPn8, statusPn9};
        bnArr = new JButton[]{statusBn0, statusBn1, statusBn2, statusBn3, statusBn4, statusBn5, statusBn6, statusBn7, statusBn8, statusBn9};
        
        //set tooltip for car picture
        this.carpic0.setToolTipText(hps.ShowCarDetail(0));
        this.carpic1.setToolTipText(hps.ShowCarDetail(1));
        this.carpic2.setToolTipText(hps.ShowCarDetail(2));
        this.carpic3.setToolTipText(hps.ShowCarDetail(3));
        this.carpic4.setToolTipText(hps.ShowCarDetail(4));
        this.carpic5.setToolTipText(hps.ShowCarDetail(5));
        this.carpic6.setToolTipText(hps.ShowCarDetail(6));
        this.carpic7.setToolTipText(hps.ShowCarDetail(7));
        this.carpic8.setToolTipText(hps.ShowCarDetail(8));
        this.carpic9.setToolTipText(hps.ShowCarDetail(9));
        
        //checkslot for table
        hps.checkslot(this);
    }
    
    public HomepageSystem getHps(){
        return this.hps;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        usernamePn = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        usernameTxt = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        mainPn = new javax.swing.JPanel();
        MenuBar = new javax.swing.JPanel();
        HomeButton = new javax.swing.JButton();
        CustomButton = new javax.swing.JButton();
        EquipmentButton = new javax.swing.JButton();
        WarehouseButton = new javax.swing.JButton();
        InvoiceButton = new javax.swing.JButton();
        AccountButton = new javax.swing.JButton();
        submainPn = new javax.swing.JPanel();
        tablePn = new javax.swing.JPanel();
        slot0 = new javax.swing.JPanel();
        statusPn0 = new javax.swing.JPanel();
        carpic0 = new javax.swing.JLabel();
        statusBn0 = new javax.swing.JButton();
        txtNocar0 = new javax.swing.JLabel();
        num1 = new javax.swing.JLabel();
        slot1 = new javax.swing.JPanel();
        statusPn1 = new javax.swing.JPanel();
        carpic1 = new javax.swing.JLabel();
        statusBn1 = new javax.swing.JButton();
        txtNocar1 = new javax.swing.JLabel();
        num2 = new javax.swing.JLabel();
        slot2 = new javax.swing.JPanel();
        statusPn2 = new javax.swing.JPanel();
        carpic2 = new javax.swing.JLabel();
        statusBn2 = new javax.swing.JButton();
        txtNocar2 = new javax.swing.JLabel();
        num3 = new javax.swing.JLabel();
        slot3 = new javax.swing.JPanel();
        statusPn3 = new javax.swing.JPanel();
        carpic3 = new javax.swing.JLabel();
        statusBn3 = new javax.swing.JButton();
        txtNocar3 = new javax.swing.JLabel();
        num4 = new javax.swing.JLabel();
        slot4 = new javax.swing.JPanel();
        statusPn4 = new javax.swing.JPanel();
        carpic4 = new javax.swing.JLabel();
        statusBn4 = new javax.swing.JButton();
        txtNocar4 = new javax.swing.JLabel();
        num5 = new javax.swing.JLabel();
        slot5 = new javax.swing.JPanel();
        statusPn5 = new javax.swing.JPanel();
        carpic5 = new javax.swing.JLabel();
        statusBn5 = new javax.swing.JButton();
        txtNocar5 = new javax.swing.JLabel();
        num6 = new javax.swing.JLabel();
        slot6 = new javax.swing.JPanel();
        statusPn6 = new javax.swing.JPanel();
        carpic6 = new javax.swing.JLabel();
        statusBn6 = new javax.swing.JButton();
        txtNocar6 = new javax.swing.JLabel();
        num7 = new javax.swing.JLabel();
        slot7 = new javax.swing.JPanel();
        statusPn7 = new javax.swing.JPanel();
        carpic7 = new javax.swing.JLabel();
        statusBn7 = new javax.swing.JButton();
        txtNocar7 = new javax.swing.JLabel();
        num8 = new javax.swing.JLabel();
        slot8 = new javax.swing.JPanel();
        statusPn8 = new javax.swing.JPanel();
        carpic8 = new javax.swing.JLabel();
        statusBn8 = new javax.swing.JButton();
        txtNocar8 = new javax.swing.JLabel();
        num9 = new javax.swing.JLabel();
        slot9 = new javax.swing.JPanel();
        statusPn9 = new javax.swing.JPanel();
        carpic9 = new javax.swing.JLabel();
        statusBn9 = new javax.swing.JButton();
        txtNocar9 = new javax.swing.JLabel();
        num10 = new javax.swing.JLabel();
        headtextPn = new javax.swing.JPanel();
        headTxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dumrongruay");
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);

        Header.setBackground(new java.awt.Color(247, 127, 0));
        Header.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Header.setPreferredSize(new java.awt.Dimension(1280, 50));
        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernamePn.setBackground(new java.awt.Color(247, 127, 0));
        usernamePn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TestIcon/userWithcircle.png"))); // NOI18N
        usernamePn.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        usernameTxt.setBackground(new java.awt.Color(255, 255, 255));
        usernameTxt.setText("@USERNAME");
        usernameTxt.setToolTipText("Username Account");
        usernameTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        usernamePn.add(usernameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 80, 30));

        Header.add(usernamePn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 10, 130, 30));

        jLabel1.setBackground(new java.awt.Color(242, 157, 0));
        jLabel1.setFont(new java.awt.Font("IrisUPC", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ดำรงรวยการช่าง ");
        Header.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, 40));

        getContentPane().add(Header, java.awt.BorderLayout.PAGE_START);

        MenuBar.setBackground(new java.awt.Color(248, 245, 228));
        MenuBar.setPreferredSize(new java.awt.Dimension(200, 670));
        MenuBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HomeButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        HomeButton.setForeground(new java.awt.Color(255, 102, 0));
        HomeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TestIcon/HomeWhite.png"))); // NOI18N
        HomeButton.setText("หน้าหลัก");
        HomeButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        HomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonActionPerformed(evt);
            }
        });
        MenuBar.add(HomeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 30, 220, 70));

        CustomButton.setBackground(new java.awt.Color(255, 102, 0));
        CustomButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        CustomButton.setForeground(new java.awt.Color(255, 255, 255));
        CustomButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TestIcon/CarManageOrange.png"))); // NOI18N
        CustomButton.setText("จัดการคิวรถ");
        CustomButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CustomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomButtonActionPerformed(evt);
            }
        });
        MenuBar.add(CustomButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 130, 220, 70));

        EquipmentButton.setBackground(new java.awt.Color(255, 102, 0));
        EquipmentButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        EquipmentButton.setForeground(new java.awt.Color(255, 255, 255));
        EquipmentButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TestIcon/ShopOrange.png"))); // NOI18N
        EquipmentButton.setText("เบิกอุปกรณ์");
        EquipmentButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        EquipmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EquipmentButtonActionPerformed(evt);
            }
        });
        MenuBar.add(EquipmentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 230, 220, 70));

        WarehouseButton.setBackground(new java.awt.Color(255, 102, 0));
        WarehouseButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        WarehouseButton.setForeground(new java.awt.Color(255, 255, 255));
        WarehouseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TestIcon/StorageOrange.png"))); // NOI18N
        WarehouseButton.setText("คลังอุปกรณ์");
        WarehouseButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        WarehouseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WarehouseButtonActionPerformed(evt);
            }
        });
        MenuBar.add(WarehouseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 330, 220, 70));

        InvoiceButton.setBackground(new java.awt.Color(255, 102, 0));
        InvoiceButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        InvoiceButton.setForeground(new java.awt.Color(255, 255, 255));
        InvoiceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TestIcon/InvoiceOrange.png"))); // NOI18N
        InvoiceButton.setText("ใบเสร็จ");
        InvoiceButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        InvoiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InvoiceButtonActionPerformed(evt);
            }
        });
        MenuBar.add(InvoiceButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 430, 220, 70));

        AccountButton.setBackground(new java.awt.Color(255, 102, 0));
        AccountButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        AccountButton.setForeground(new java.awt.Color(255, 255, 255));
        AccountButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TestIcon/AccountOrange.png"))); // NOI18N
        AccountButton.setText("จัดการพนักงาน");
        AccountButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccountButtonActionPerformed(evt);
            }
        });
        MenuBar.add(AccountButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 530, 220, 70));

        submainPn.setBackground(new java.awt.Color(255, 255, 255));
        submainPn.setForeground(new java.awt.Color(255, 255, 255));
        submainPn.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 30));

        tablePn.setBackground(new java.awt.Color(255, 255, 255));

        slot0.setBackground(new java.awt.Color(78, 80, 82));
        slot0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        slot0.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        statusPn0.setBackground(new java.awt.Color(255, 255, 255));
        statusPn0.setForeground(new java.awt.Color(255, 255, 255));
        statusPn0.setToolTipText("");
        statusPn0.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        carpic0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TestIcon/car.png"))); // NOI18N

        statusBn0.setBackground(new java.awt.Color(78, 80, 82));
        statusBn0.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        statusBn0.setForeground(new java.awt.Color(255, 255, 255));
        statusBn0.setText("สถานะ");
        statusBn0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout statusPn0Layout = new javax.swing.GroupLayout(statusPn0);
        statusPn0.setLayout(statusPn0Layout);
        statusPn0Layout.setHorizontalGroup(
            statusPn0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPn0Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(carpic0)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(statusPn0Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusBn0, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                .addContainerGap())
        );
        statusPn0Layout.setVerticalGroup(
            statusPn0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPn0Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(carpic0)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(statusBn0, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        slot0.add(statusPn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 140, 200));

        txtNocar0.setBackground(new java.awt.Color(255, 255, 255));
        txtNocar0.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        txtNocar0.setForeground(java.awt.Color.white);
        txtNocar0.setText("< ว่าง >");
        slot0.add(txtNocar0, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        num1.setBackground(new java.awt.Color(255, 255, 255));
        num1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        num1.setForeground(java.awt.Color.white);
        num1.setText("1");
        slot0.add(num1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 20, -1));

        slot1.setBackground(new java.awt.Color(78, 80, 82));
        slot1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        slot1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        statusPn1.setBackground(new java.awt.Color(255, 255, 255));
        statusPn1.setForeground(new java.awt.Color(255, 255, 255));

        carpic1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TestIcon/car.png"))); // NOI18N

        statusBn1.setBackground(new java.awt.Color(78, 80, 82));
        statusBn1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        statusBn1.setForeground(new java.awt.Color(255, 255, 255));
        statusBn1.setText("สถานะ");
        statusBn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        statusBn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusBn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout statusPn1Layout = new javax.swing.GroupLayout(statusPn1);
        statusPn1.setLayout(statusPn1Layout);
        statusPn1Layout.setHorizontalGroup(
            statusPn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPn1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(carpic1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(statusPn1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusBn1, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                .addContainerGap())
        );
        statusPn1Layout.setVerticalGroup(
            statusPn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPn1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(carpic1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(statusBn1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        slot1.add(statusPn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 140, 200));

        txtNocar1.setBackground(new java.awt.Color(255, 255, 255));
        txtNocar1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        txtNocar1.setForeground(java.awt.Color.white);
        txtNocar1.setText("< ว่าง >");
        slot1.add(txtNocar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        num2.setBackground(new java.awt.Color(255, 255, 255));
        num2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        num2.setForeground(java.awt.Color.white);
        num2.setText("2");
        slot1.add(num2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 20, -1));

        slot2.setBackground(new java.awt.Color(78, 80, 82));
        slot2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        slot2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        statusPn2.setBackground(new java.awt.Color(255, 255, 255));
        statusPn2.setForeground(new java.awt.Color(255, 255, 255));

        carpic2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TestIcon/car.png"))); // NOI18N

        statusBn2.setBackground(new java.awt.Color(78, 80, 82));
        statusBn2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        statusBn2.setForeground(new java.awt.Color(255, 255, 255));
        statusBn2.setText("สถานะ");
        statusBn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        statusBn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusBn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout statusPn2Layout = new javax.swing.GroupLayout(statusPn2);
        statusPn2.setLayout(statusPn2Layout);
        statusPn2Layout.setHorizontalGroup(
            statusPn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPn2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(carpic2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(statusPn2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusBn2, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                .addContainerGap())
        );
        statusPn2Layout.setVerticalGroup(
            statusPn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPn2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(carpic2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(statusBn2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        slot2.add(statusPn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 140, 200));

        txtNocar2.setBackground(new java.awt.Color(255, 255, 255));
        txtNocar2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        txtNocar2.setForeground(java.awt.Color.white);
        txtNocar2.setText("< ว่าง >");
        slot2.add(txtNocar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        num3.setBackground(new java.awt.Color(255, 255, 255));
        num3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        num3.setForeground(java.awt.Color.white);
        num3.setText("3");
        slot2.add(num3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 20, -1));

        slot3.setBackground(new java.awt.Color(78, 80, 82));
        slot3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        slot3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        statusPn3.setBackground(new java.awt.Color(255, 255, 255));
        statusPn3.setForeground(new java.awt.Color(255, 255, 255));

        carpic3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TestIcon/car.png"))); // NOI18N

        statusBn3.setBackground(new java.awt.Color(78, 80, 82));
        statusBn3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        statusBn3.setForeground(new java.awt.Color(255, 255, 255));
        statusBn3.setText("สถานะ");
        statusBn3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout statusPn3Layout = new javax.swing.GroupLayout(statusPn3);
        statusPn3.setLayout(statusPn3Layout);
        statusPn3Layout.setHorizontalGroup(
            statusPn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPn3Layout.createSequentialGroup()
                .addGroup(statusPn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(statusPn3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(statusBn3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(statusPn3Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(carpic3)))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        statusPn3Layout.setVerticalGroup(
            statusPn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPn3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(carpic3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(statusBn3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        slot3.add(statusPn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 140, 200));

        txtNocar3.setBackground(new java.awt.Color(255, 255, 255));
        txtNocar3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        txtNocar3.setForeground(java.awt.Color.white);
        txtNocar3.setText("< ว่าง >");
        slot3.add(txtNocar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        num4.setBackground(new java.awt.Color(255, 255, 255));
        num4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        num4.setForeground(java.awt.Color.white);
        num4.setText("4");
        slot3.add(num4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 20, -1));

        slot4.setBackground(new java.awt.Color(78, 80, 82));
        slot4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        slot4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        statusPn4.setBackground(new java.awt.Color(255, 255, 255));
        statusPn4.setForeground(new java.awt.Color(255, 255, 255));

        carpic4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TestIcon/car.png"))); // NOI18N

        statusBn4.setBackground(new java.awt.Color(78, 80, 82));
        statusBn4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        statusBn4.setForeground(new java.awt.Color(255, 255, 255));
        statusBn4.setText("สถานะ");
        statusBn4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        statusBn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusBn4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout statusPn4Layout = new javax.swing.GroupLayout(statusPn4);
        statusPn4.setLayout(statusPn4Layout);
        statusPn4Layout.setHorizontalGroup(
            statusPn4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPn4Layout.createSequentialGroup()
                .addGroup(statusPn4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(statusPn4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(statusBn4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(statusPn4Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(carpic4)))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        statusPn4Layout.setVerticalGroup(
            statusPn4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPn4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(carpic4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(statusBn4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        slot4.add(statusPn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 140, 200));

        txtNocar4.setBackground(new java.awt.Color(255, 255, 255));
        txtNocar4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        txtNocar4.setForeground(java.awt.Color.white);
        txtNocar4.setText("< ว่าง >");
        slot4.add(txtNocar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        num5.setBackground(new java.awt.Color(255, 255, 255));
        num5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        num5.setForeground(java.awt.Color.white);
        num5.setText("5");
        slot4.add(num5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 20, -1));

        slot5.setBackground(new java.awt.Color(78, 80, 82));
        slot5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        slot5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        statusPn5.setBackground(new java.awt.Color(255, 255, 255));
        statusPn5.setForeground(new java.awt.Color(255, 255, 255));

        carpic5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TestIcon/car.png"))); // NOI18N

        statusBn5.setBackground(new java.awt.Color(78, 80, 82));
        statusBn5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        statusBn5.setForeground(new java.awt.Color(255, 255, 255));
        statusBn5.setText("สถานะ");
        statusBn5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout statusPn5Layout = new javax.swing.GroupLayout(statusPn5);
        statusPn5.setLayout(statusPn5Layout);
        statusPn5Layout.setHorizontalGroup(
            statusPn5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPn5Layout.createSequentialGroup()
                .addGroup(statusPn5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(statusPn5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(statusBn5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(statusPn5Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(carpic5)))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        statusPn5Layout.setVerticalGroup(
            statusPn5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPn5Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(carpic5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(statusBn5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        slot5.add(statusPn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 140, 200));

        txtNocar5.setBackground(new java.awt.Color(255, 255, 255));
        txtNocar5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        txtNocar5.setForeground(java.awt.Color.white);
        txtNocar5.setText("< ว่าง >");
        slot5.add(txtNocar5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        num6.setBackground(new java.awt.Color(255, 255, 255));
        num6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        num6.setForeground(java.awt.Color.white);
        num6.setText("6");
        slot5.add(num6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 20, -1));

        slot6.setBackground(new java.awt.Color(78, 80, 82));
        slot6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        slot6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        statusPn6.setBackground(new java.awt.Color(255, 255, 255));
        statusPn6.setForeground(new java.awt.Color(255, 255, 255));

        carpic6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TestIcon/car.png"))); // NOI18N

        statusBn6.setBackground(new java.awt.Color(78, 80, 82));
        statusBn6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        statusBn6.setForeground(new java.awt.Color(255, 255, 255));
        statusBn6.setText("สถานะ");
        statusBn6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout statusPn6Layout = new javax.swing.GroupLayout(statusPn6);
        statusPn6.setLayout(statusPn6Layout);
        statusPn6Layout.setHorizontalGroup(
            statusPn6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPn6Layout.createSequentialGroup()
                .addGroup(statusPn6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(statusPn6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(statusBn6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(statusPn6Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(carpic6)))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        statusPn6Layout.setVerticalGroup(
            statusPn6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPn6Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(carpic6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(statusBn6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        slot6.add(statusPn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 140, 200));

        txtNocar6.setBackground(new java.awt.Color(255, 255, 255));
        txtNocar6.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        txtNocar6.setForeground(java.awt.Color.white);
        txtNocar6.setText("< ว่าง >");
        slot6.add(txtNocar6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        num7.setBackground(new java.awt.Color(255, 255, 255));
        num7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        num7.setForeground(java.awt.Color.white);
        num7.setText("7");
        slot6.add(num7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 20, -1));

        slot7.setBackground(new java.awt.Color(78, 80, 82));
        slot7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        slot7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        statusPn7.setBackground(new java.awt.Color(255, 255, 255));
        statusPn7.setForeground(new java.awt.Color(255, 255, 255));

        carpic7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TestIcon/car.png"))); // NOI18N

        statusBn7.setBackground(new java.awt.Color(78, 80, 82));
        statusBn7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        statusBn7.setForeground(new java.awt.Color(255, 255, 255));
        statusBn7.setText("สถานะ");
        statusBn7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        statusBn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusBn7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout statusPn7Layout = new javax.swing.GroupLayout(statusPn7);
        statusPn7.setLayout(statusPn7Layout);
        statusPn7Layout.setHorizontalGroup(
            statusPn7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPn7Layout.createSequentialGroup()
                .addGroup(statusPn7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(statusPn7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(statusBn7, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(statusPn7Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(carpic7)))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        statusPn7Layout.setVerticalGroup(
            statusPn7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPn7Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(carpic7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(statusBn7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        slot7.add(statusPn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 140, 200));

        txtNocar7.setBackground(new java.awt.Color(255, 255, 255));
        txtNocar7.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        txtNocar7.setForeground(java.awt.Color.white);
        txtNocar7.setText("< ว่าง >");
        slot7.add(txtNocar7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        num8.setBackground(new java.awt.Color(255, 255, 255));
        num8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        num8.setForeground(java.awt.Color.white);
        num8.setText("8");
        slot7.add(num8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 20, -1));

        slot8.setBackground(new java.awt.Color(78, 80, 82));
        slot8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        slot8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        statusPn8.setBackground(new java.awt.Color(255, 255, 255));
        statusPn8.setForeground(new java.awt.Color(255, 255, 255));

        carpic8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TestIcon/car.png"))); // NOI18N

        statusBn8.setBackground(new java.awt.Color(78, 80, 82));
        statusBn8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        statusBn8.setForeground(new java.awt.Color(255, 255, 255));
        statusBn8.setText("สถานะ");
        statusBn8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout statusPn8Layout = new javax.swing.GroupLayout(statusPn8);
        statusPn8.setLayout(statusPn8Layout);
        statusPn8Layout.setHorizontalGroup(
            statusPn8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPn8Layout.createSequentialGroup()
                .addGroup(statusPn8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(statusPn8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(statusBn8, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(statusPn8Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(carpic8)))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        statusPn8Layout.setVerticalGroup(
            statusPn8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPn8Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(carpic8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(statusBn8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        slot8.add(statusPn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 140, 200));

        txtNocar8.setBackground(new java.awt.Color(255, 255, 255));
        txtNocar8.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        txtNocar8.setForeground(java.awt.Color.white);
        txtNocar8.setText("< ว่าง >");
        slot8.add(txtNocar8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        num9.setBackground(new java.awt.Color(255, 255, 255));
        num9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        num9.setForeground(java.awt.Color.white);
        num9.setText("9");
        slot8.add(num9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 20, -1));

        slot9.setBackground(new java.awt.Color(78, 80, 82));
        slot9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        slot9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        statusPn9.setBackground(new java.awt.Color(255, 255, 255));
        statusPn9.setForeground(new java.awt.Color(255, 255, 255));

        carpic9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TestIcon/car.png"))); // NOI18N

        statusBn9.setBackground(new java.awt.Color(78, 80, 82));
        statusBn9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        statusBn9.setForeground(new java.awt.Color(255, 255, 255));
        statusBn9.setText("สถานะ");
        statusBn9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout statusPn9Layout = new javax.swing.GroupLayout(statusPn9);
        statusPn9.setLayout(statusPn9Layout);
        statusPn9Layout.setHorizontalGroup(
            statusPn9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPn9Layout.createSequentialGroup()
                .addGroup(statusPn9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(statusPn9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(statusBn9, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(statusPn9Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(carpic9)))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        statusPn9Layout.setVerticalGroup(
            statusPn9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPn9Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(carpic9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(statusBn9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        slot9.add(statusPn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 140, 200));

        txtNocar9.setBackground(new java.awt.Color(255, 255, 255));
        txtNocar9.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        txtNocar9.setForeground(java.awt.Color.white);
        txtNocar9.setText("< ว่าง >");
        slot9.add(txtNocar9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        num10.setBackground(new java.awt.Color(255, 255, 255));
        num10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        num10.setForeground(java.awt.Color.white);
        num10.setText("10");
        slot9.add(num10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 30, -1));

        headtextPn.setBackground(new java.awt.Color(78, 80, 82));
        headtextPn.setToolTipText("test");

        headTxt.setBackground(new java.awt.Color(255, 204, 102));
        headTxt.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        headTxt.setForeground(new java.awt.Color(255, 255, 255));
        headTxt.setText("สถานะการซ่อมรถ");
        headtextPn.add(headTxt);

        javax.swing.GroupLayout tablePnLayout = new javax.swing.GroupLayout(tablePn);
        tablePn.setLayout(tablePnLayout);
        tablePnLayout.setHorizontalGroup(
            tablePnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablePnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tablePnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(headtextPn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(tablePnLayout.createSequentialGroup()
                        .addComponent(slot5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(slot6, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(slot7, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(slot8, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(slot9, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tablePnLayout.createSequentialGroup()
                        .addComponent(slot0, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(slot1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(slot2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(slot3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(slot4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tablePnLayout.setVerticalGroup(
            tablePnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tablePnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headtextPn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tablePnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(slot1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(slot0, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(slot4, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(slot3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(slot2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tablePnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(slot6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(slot5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(slot9, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(slot8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(slot7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );

        submainPn.add(tablePn);

        javax.swing.GroupLayout mainPnLayout = new javax.swing.GroupLayout(mainPn);
        mainPn.setLayout(mainPnLayout);
        mainPnLayout.setHorizontalGroup(
            mainPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPnLayout.createSequentialGroup()
                .addComponent(MenuBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(submainPn, javax.swing.GroupLayout.PREFERRED_SIZE, 1064, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        mainPnLayout.setVerticalGroup(
            mainPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPnLayout.createSequentialGroup()
                .addComponent(MenuBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(submainPn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(mainPn, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void statusBn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusBn7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusBn7ActionPerformed

    private void statusBn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusBn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusBn2ActionPerformed

    private void statusBn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusBn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusBn1ActionPerformed

    private void statusBn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusBn4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusBn4ActionPerformed

    private void HomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HomeButtonActionPerformed

    private void CustomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustomButtonActionPerformed

    private void EquipmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EquipmentButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EquipmentButtonActionPerformed

    private void WarehouseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WarehouseButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WarehouseButtonActionPerformed

    private void InvoiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InvoiceButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InvoiceButtonActionPerformed

    private void AccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AccountButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // look and feel setting
                try {
                    UIManager.setLookAndFeel(new FlatLightLaf());
                }catch(UnsupportedLookAndFeelException ex){
                    ex.printStackTrace();
                }
                HomepageFrame home = new HomepageFrame(null, null);
                home.setSize(1280, 720);
                home.setVisible(true);
            }
        });
    }
    
    public JLabel getUsernameLabel(){
        return this.usernameTxt;
    }
    
    @Override
    public JButton getManagementButton(){
        return this.CustomButton;
    }
    
    @Override
    public JButton getEquipmentButton(){
        return this.EquipmentButton;
    }
    
    @Override
    public JButton getWarehouseButton(){
        return this.WarehouseButton;
    }
    
    @Override
    public JButton getReceiptButton(){
        return this.InvoiceButton;
    }
    
    //update slot
    public void update(){
        hps.checkslot(this);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AccountButton;
    private javax.swing.JButton CustomButton;
    private javax.swing.JButton EquipmentButton;
    private javax.swing.JPanel Header;
    private javax.swing.JButton HomeButton;
    private javax.swing.JButton InvoiceButton;
    private javax.swing.JPanel MenuBar;
    private javax.swing.JButton WarehouseButton;
    private javax.swing.JLabel carpic0;
    private javax.swing.JLabel carpic1;
    private javax.swing.JLabel carpic2;
    private javax.swing.JLabel carpic3;
    private javax.swing.JLabel carpic4;
    private javax.swing.JLabel carpic5;
    private javax.swing.JLabel carpic6;
    private javax.swing.JLabel carpic7;
    private javax.swing.JLabel carpic8;
    private javax.swing.JLabel carpic9;
    private javax.swing.JLabel headTxt;
    private javax.swing.JPanel headtextPn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel mainPn;
    private javax.swing.JLabel num1;
    private javax.swing.JLabel num10;
    private javax.swing.JLabel num2;
    private javax.swing.JLabel num3;
    private javax.swing.JLabel num4;
    private javax.swing.JLabel num5;
    private javax.swing.JLabel num6;
    private javax.swing.JLabel num7;
    private javax.swing.JLabel num8;
    private javax.swing.JLabel num9;
    private javax.swing.JPanel slot0;
    private javax.swing.JPanel slot1;
    private javax.swing.JPanel slot2;
    private javax.swing.JPanel slot3;
    private javax.swing.JPanel slot4;
    private javax.swing.JPanel slot5;
    private javax.swing.JPanel slot6;
    private javax.swing.JPanel slot7;
    private javax.swing.JPanel slot8;
    private javax.swing.JPanel slot9;
    protected javax.swing.JButton statusBn0;
    protected javax.swing.JButton statusBn1;
    protected javax.swing.JButton statusBn2;
    protected javax.swing.JButton statusBn3;
    protected javax.swing.JButton statusBn4;
    protected javax.swing.JButton statusBn5;
    protected javax.swing.JButton statusBn6;
    protected javax.swing.JButton statusBn7;
    protected javax.swing.JButton statusBn8;
    protected javax.swing.JButton statusBn9;
    protected javax.swing.JPanel statusPn0;
    protected javax.swing.JPanel statusPn1;
    protected javax.swing.JPanel statusPn2;
    protected javax.swing.JPanel statusPn3;
    protected javax.swing.JPanel statusPn4;
    protected javax.swing.JPanel statusPn5;
    protected javax.swing.JPanel statusPn6;
    protected javax.swing.JPanel statusPn7;
    protected javax.swing.JPanel statusPn8;
    protected javax.swing.JPanel statusPn9;
    private javax.swing.JPanel submainPn;
    private javax.swing.JPanel tablePn;
    private javax.swing.JLabel txtNocar0;
    private javax.swing.JLabel txtNocar1;
    private javax.swing.JLabel txtNocar2;
    private javax.swing.JLabel txtNocar3;
    private javax.swing.JLabel txtNocar4;
    private javax.swing.JLabel txtNocar5;
    private javax.swing.JLabel txtNocar6;
    private javax.swing.JLabel txtNocar7;
    private javax.swing.JLabel txtNocar8;
    private javax.swing.JLabel txtNocar9;
    private javax.swing.JPanel usernamePn;
    private javax.swing.JLabel usernameTxt;
    // End of variables declaration//GEN-END:variables

    @Override
    public JButton getHomeButton() {
        return null;
    }

    @Override
    public JButton getStuffManageButton() {
        return this.AccountButton;
    }
}
